use master;
create database [db.email];
GO
use [db.email];
CREATE TABLE [dbo].[Emails](
	[Id] INT IDENTITY(1,1) NOT NULL,
	[To] VARCHAR(40) NOT NULL,
	[From] VARCHAR(40) NOT NULL,
	[Body] VARCHAR(MAX) NOT NULL
 CONSTRAINT [PK_Emails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


