use master;
create database [db.email];
GO
use [db.email];
CREATE TABLE [dbo].[Emails](
	[Id] INT IDENTITY(1,1) NOT NULL,
	[To] VARCHAR(40) NOT NULL,
	[From] VARCHAR(40) NOT NULL,
	[Body] VARCHAR(MAX) NOT NULL,
	[UserId] INT NOT NULL
 CONSTRAINT [PK_Emails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
GO
use master;
create database [db.user];
GO
use [db.user];
CREATE TABLE [dbo].[Users](
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Email] VARCHAR(40) NOT NULL,
	[Password] VARCHAR(40) NOT NULL
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
use master;
create database [db.workout];
GO
use [db.workout];
CREATE TABLE [dbo].[Workouts](
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Title] VARCHAR(40) NOT NULL,
	[CreatedOn] DATETIME NOT NULL,
	[UserId] INT NOT NULL
 CONSTRAINT [PK_Workouts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


